### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by malusev998** [matttproud/golang_protobuf_extensions#19]
After the release of v1.0.3 this library is no longer backwards compatible with the old proto.Message interface

[V1 Message Interface](https://pkg.go.dev/google.golang.org/protobuf@v1.28.1/runtime/protoiface#MessageV1)
```
type MessageV1 interface {
	Reset()
	String() [string](https://pkg.go.dev/builtin#string)
	ProtoMessage()
}
```

After the import of new protobuf package from `google.golang.org/protobuf/proto` proto.Message is `https://pkg.go.dev/google.golang.org/protobuf@v1.28.1/reflect/protoreflect#ProtoMessage`

```
type ProtoMessage interface{ 
   ProtoReflect() Message 
}
```

This currently breaks `https://github.com/prometheus/common/blob/main/expfmt/decode.go`

```
go/pkg/mod/github.com/prometheus/common@v0.37.0/expfmt/decode.go:89:38: cannot use v (variable of type *io_prometheus_client.MetricFamily) as type protoreflect.ProtoMessage in argument to pbutil.ReadDelimited:
        *io_prometheus_client.MetricFamily does not implement protoreflect.ProtoMessage (missing ProtoReflect method)

go/pkg/mod/github.com/prometheus/common@v0.37.0/expfmt/encode.go:120:40: cannot use v (variable of type *io_prometheus_client.MetricFamily) as type protoreflect.ProtoMessage in argument to pbutil.WriteDelimited:
        *io_prometheus_client.MetricFamily does not implement protoreflect.ProtoMessage (missing ProtoReflect method)
```
Could you please remove this release and tag it with v2.0.0 or something?

**Comment by matttproud** [comment]
Pin to v1.0.2 in the interim.  I will move this to another major version
within a day or two.

Nicola Asuni (Vonage) ***@***.***> schrieb am Di. 25. Okt.
2022 um 11:58:

**Comment by nomad-software** [comment]
Hi @matttproud could this be worked on as a priority please this is a big breaking change and just took me ages to find the cause. Thanks.

**Comment by matttproud** [comment]
As I said, yes, I will address soon.  I am currently about 200km from my
laptop, so you will need to have some patience.  Please either pin to
v1.0.2 or upgrade your Protocol Buffer version and message assets.

Gary Willoughby ***@***.***> schrieb am Di. 25. Okt. 2022 um
12:29:

**Comment by malusev998** [comment]
Thank you for your time, hope it will be fixed soon.

**Comment by nomad-software** [comment]
> Please either pin to v1.0.2 or upgrade your Protocol Buffer version and message assets.

The issue in my case is that this library is a transitive dependency of [Prometheus](https://github.com/prometheus/client_golang).

I can pin it in my `go.mod` and it compiles fine, which is good. I guess a lot more people are going to have the same issue.

**Comment by malusev998** [comment]
> > Please either pin to v1.0.2 or upgrade your Protocol Buffer version and message assets.
> 
> The issue in my case is that this library is a transitive dependency of [Prometheus](https://github.com/prometheus/client_golang).
> 
> I can pin it in my `go.mod` and it compiles fine, which is good. I guess a lot more people are going to have the same issue.

As I can see, this library is used in Prometheus common library and their GRPC models are not generated with new grpc version aka `google.golang.org/protobuf/proto`. Most likely as this will be breaking change for them and they don't want that.
Haven't seen this library used anywhere else except in Prometheus lib

**Comment by matttproud** [comment]
My main mistake was assuming that the generated Protocol Buffer message
assets were forward-compatible (I recall hearing that they were supposed to
be), so clearly this is not a patch revision.  My apologies.  If you can,
work with partners to depend to v1.0.2 in the interim.  You will get a fix
for this when I am back at a computer.

Dusan Malusev ***@***.***> schrieb am Di. 25. Okt. 2022 um
13:14:

**Comment by matttproud** [comment]
Thanks for bearing with me on this.  I apologize for any inconvenience this caused.  I was on the other side of Alps from my computer by the time the first defect report arose, which was why I couldn't immediately rectify this.

I have pushed a new tag [`v1.0.4`](https://github.com/matttproud/golang_protobuf_extensions/releases/tag/v1.0.4), which is pinned to the [`v1.0.2`](https://github.com/matttproud/golang_protobuf_extensions/releases/tag/v1.0.2) code.  For now, the behavior of `v1.0.4` and similar now lives in a legacy [`v1`](https://github.com/matttproud/golang_protobuf_extensions/tree/v1) branch.  I expect that branch to go dormant long-term with a subsequent update that provides [deprecation notices](https://rakyll.org/deprecated/) on the old APIs advising users to migrate to a new major version 2.

Going forward, the `master` branch will take the code of [`v1.0.3`](https://github.com/matttproud/golang_protobuf_extensions/releases/tag/v1.0.3) and track what is today's current Protocol Buffer implementation and generated code API.  This will become major version 2.  Users  should adapt to this where possible, though there is no need to worry that `v1` will go away.  Migrating to version 2 will require updating both the version of the Protocol Buffer library you use as well as any generated Protocol Buffer message file assets.  For small and medium projects, this should be a simple affair.  I will cut a version 2 release soon hereafter.

My instinct told me before cutting `v1.0.3` I should have made a new major version instead, but I was not 100% certain due to [these reasons](https://github.com/matttproud/golang_protobuf_extensions/issues/19#issuecomment-1290386160).  And then there is some extra ceremony involved with [creating new module major versions](https://go.dev/doc/modules/major-version).
